version: "3.8"
services:
  mysql_principal:
    container_name: Maestro1
    image: mysql:8.0
    ports:
      - "3316:3306"
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=examenad
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examenad
    volumes:
      - master_datos:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_secundario:
    container_name: Esclavo1
    image: mysql:8.0
    ports:
      - "3317:3306"
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --binlog-do-db=examenad
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examenad
    volumes:
      - slave_datos:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql    

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOSTS: "mysql_principal,mysql_secundario"
      PMA_ARBITRARY: 1

  servidor1:
    image: python:3.9-slim
    build:
      context: ./servidor1
      dockerfile: Dockerfile
    container_name: ServidorWeb0001
    ports:
      - "5001:5000"
    depends_on:
      - mysql_principal
    command: python app.py

  servidor2:
    image: python:3.9-slim
    build:
      context: ./servidor2
      dockerfile: Dockerfile
    container_name: ServidorWeb0002
    ports:
      - "5002:5000"
    depends_on:
      - mysql_principal
    command: python app.py

  reducer:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    container_name: ServidorWeb0003
    ports:
      - "5003:5000"
    depends_on:
      - servidor1
      - servidor2
    command: python app.py

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx0001
    ports:
      - "8080:80"
    depends_on:
      - servidor1
      - servidor2

volumes:
  master_datos:
    driver: local
  slave_datos:
    driver: local



