events { }

http {
    upstream servidores {
        server servidor1:5000 weight=5;
        server servidor2:5000 weight=4;
    }

    server {
        listen 80;

        location / {
            proxy_pass         http://servidores;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
